// <auto-generated />
using CityWeather.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CityWeather.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    [Migration("20221006082804_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("CityWeather.Data.cityData", b =>
                {
                    b.Property<int>("cityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cityName")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("counteryName")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("cityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            cityId = 1,
                            cityName = "Amsterdam",
                            counteryName = "Netherlands"
                        },
                        new
                        {
                            cityId = 2,
                            cityName = "Paris",
                            counteryName = "France"
                        },
                        new
                        {
                            cityId = 3,
                            cityName = "Cairo",
                            counteryName = "Egypt"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
